### ISSUE TITLE
a  problem for training

### ISSUE THREAD

**Issue by qqqqhhqq** [rlqja1107/torch-LLM4SGG#2]
Hello, thank you for your contribution to the community. I would like to know the requirements for computing power in your job? And the situation of the training cycle

**Comment by rlqja1107** [comment]
Thank you for your interest in my work!

For implementing the codes, i used A6000 GPU with 48GB RAM. However, it seems to be okay when you run with the smaller RAM. I think the GPU with 20GB would be fine.

Furthermore, regarding to the training cycle, 120,000 iterations (2~3 epochs) are enough to reach the optimal performance. After that, the performance changes at the first decimal place.

Thank you!
