### ISSUE TITLE
pre-trained object detector model for GQA dataset

### ISSUE THREAD

**Issue by hyp9432** [rlqja1107/torch-LLM4SGG#5]
Hello author, thank you for your interesting work!
![image](https://github.com/rlqja1107/torch-LLM4SGG/assets/97290788/6aa22135-fd59-46a9-b685-671d47195aec)
Following your suggestion, I went ahead and entered the repository of SHA-GCL-for-SGG. To my disappointment, I found that the object detector model of the GQA dataset was invalid. Could you provide the Google Drive sharing link of the object detector?

**Comment by rlqja1107** [comment]
Thank you for your interest to my work!

Basically, we leverage [GLIP](https://github.com/microsoft/GLIP) for object detector while SHA-GCL leveraged Faster R-CNN for object detector. Therefore, there is no need to download the pre-trained object detector's weight on SHA-GCL. 

GLIP is one of the object detectors that show superiority on zero-shot. Therefore, i utilize one pre-trained model (i.e., GLIP) on Visual Genome and GQA dataset. In a nutshell, you can run our code without a Faster R-CNN object detector trained on GQA dataset.

Nevertheless, i have an object detector trained on the GQA dataset. If you need it for other purpose, i will share this pre-trained weight.

**Comment by hyp9432** [comment]
Thank you for your reply, yes, I need this pre-training weight and would appreciate it if you could share it.

**Comment by rlqja1107** [comment]
Can you share your email? I'll share this pre-trained weight through your email.

**Comment by hyp9432** [comment]
My email is hyp9432@gmail.com，Thanks again for your help！
