### ISSUE TITLE
can't load from provided link

### ISSUE THREAD

**Issue by ZHUXUHAN** [rlqja1107/torch-LLM4SGG#7]
[dataset/VG/aligned_triplet_coco4vg_grounded.json](https://huggingface.co/datasets/kb-kim/LLM4SGG/resolve/main/aligned_triplet_coco4vg_grounded.json)

I can't obtain the file from this link. Can you upload it to Google Cloud?

**Comment by rlqja1107** [comment]
Hi, Thank you for your feedback on my implementation.
I uploaded all Grounded Scene Graphs files connected to Google Cloud on README.md.

Furthermore, I modified the code to automatically download the necessary files, such as aligned_triplet_coco4vg_grounded.json.
If you have a problem, feel free to contact me!

Thank you!

**Comment by ZHUXUHAN** [comment]
I know it. Thanks.
