### ISSUE TITLE
COCO_triplet_labels.npy?

### ISSUE THREAD

**Issue by ZHUXUHAN** [rlqja1107/torch-LLM4SGG#9]
where can i get this "COCO_triplet_labels.npy" file?

**Comment by rlqja1107** [comment]
You can find the related file on [/dataset/COCO/README.md](https://github.com/rlqja1107/torch-LLM4SGG/blob/master/dataset/COCO/README.md).

Specifically, You can download the corresponding file on that link.
![image](https://github.com/user-attachments/assets/3a988913-4fef-46bd-8090-01f0396ade5a)

Sorry for any confusion.

**Comment by rlqja1107** [comment]
I'll modify my code to automatically download that file.

**Comment by ZHUXUHAN** [comment]
OK, thanks.
